package fr.univpau.sma.projet.gui.market;

import jade.core.AID;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.swing.JFrame;

import fr.univpau.sma.projet.agent.MarketAgent;
import fr.univpau.sma.projet.gui.dealer.DealerAuctionCreation;
import fr.univpau.sma.projet.gui.taker.TakerModeChoice;
import fr.univpau.sma.projet.objects.Auction;
import fr.univpau.sma.projet.objects.MarketCurrentAuctionsTable;
import fr.univpau.sma.projet.objects.MarketPastAuctionsTable;


/**
 *
 * @author mraleborg
 */
@SuppressWarnings("serial")
public class MarketGUI extends javax.swing.JFrame {



	List<Auction> _Auctions = new ArrayList<Auction>();
	List<Auction> _PastAuctions = new ArrayList<Auction>();
	List<AID> _TakerAgents = new ArrayList<AID>();
	
	HashMap<AID, List<Auction>> _mappingAuctions = new HashMap<AID, List<Auction>>();
	
	MarketCurrentAuctionsTable modele;
	MarketPastAuctionsTable modele1;
	
	MarketAgent _agent;
	
    public MarketGUI(List<Auction> _Auctions,
			HashMap<AID, List<Auction>> _mappingAuctions, MarketAgent _agent)
			throws HeadlessException {
        initComponents();
		this._Auctions = _Auctions;
		this._mappingAuctions = _mappingAuctions;
		this._agent = _agent;
	}

	/**
     * Creates new form MarketGUI
     */
    public MarketGUI(MarketAgent _agent) {
    	this._agent = _agent;
        initComponents();
    }
    
    public void addAuction(Auction auction)
    {
    	this._Auctions.add(auction);
    	this.modele.addAuction(auction);
    }
    
    public void removeAuction(Auction auction)
    {
    	int i = -1;
    	for(Auction a : _Auctions)
    		if(a.compareTo(auction)==0)
    			i = _Auctions.indexOf(a);
    	if(i>-1)
    		this.modele.removeAuction(i);
    }

    public void addParticipating(AID tak, Auction auc)
    {
    	modele.addParticipating(tak, auc);
    }
    
    public void removeParticipating(AID tak)
    {
    	if(_mappingAuctions.containsKey(tak))
    	{
    		_mappingAuctions.remove(tak);
    		modele.removeParticipating(tak);
    	}
    	
    }
    
    public void addPastAuction(Auction a, String s)
    {
    	removeAuction(a);
    	
    	modele1.addAuction(a, s);
    	
    }
    
    public void updateAuction(Auction a)
    {
    	for(Auction auct : _Auctions)
    	{
    		if(auct.compareTo(a)==0)
    		{
    			_Auctions.set(_Auctions.indexOf(auct), a);
    		}
    	}
    	modele.updateAuction();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	this.setTitle("Market Agent -- Black-Market");
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		modele = new MarketCurrentAuctionsTable(_Auctions, _mappingAuctions);
		jTable1.setModel(modele);
		
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane2.addTab("Enchères en cours", jScrollPane1);

		modele1 = new MarketPastAuctionsTable();
		jTable2.setModel(modele1);
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane2.addTab("Enchères terminées", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
        

        jMenu1.setText("File");
        
        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nouveau preneur");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Nouveau preneur -- Mode manuel");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Nouveau vendeur");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);


        pack();
    }// </editor-fold>   
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {   
    	System.out.println("nouveau prenneur -- mode automatique");
    	TakerModeChoice frame = new TakerModeChoice(this._agent, true);
    	frame.setVisible(true);
    	frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    } 
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {     
    	System.out.println("nouveau vendeur");
    	DealerAuctionCreation frame = new DealerAuctionCreation(this._agent);
    	frame.setVisible(true);
    	frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    } 
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {     
    	System.out.println("nouveau prenneur -- mode manuel");
    	TakerModeChoice frame = new TakerModeChoice(this._agent, false);
    	frame.setVisible(true);
    	frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    } 

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MarketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MarketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MarketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MarketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MarketGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify            
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2; 
    private javax.swing.JMenuItem jMenuItem3;                    
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration                   
}

